import { Banknote, ClipboardList, Eye, FileText, Plus, ReceiptText } from 'lucide-react'
import type { EventRecord } from './event-data'
import { DataTable, OutlineButton, Panel, SectionHeading } from './components'

export default function Billing({ event }: { event: EventRecord }) {
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(300px,0.96fr)]"><div className="space-y-6"><div className="grid gap-4 sm:grid-cols-3"><Metric label="Total Billed" value="KSh 0.00" /><Metric label="Total Paid" value="KSh 0.00" emphasis /><Metric label="Balance Due" value="KSh 0.00" /></div><Panel><SectionHeading title="Proposals" subtitle="Event proposals and quotes" action={<button className="inline-flex items-center gap-2 rounded-md bg-[#cc2622] px-4 py-2 text-sm font-semibold text-white hover:bg-[#a01f1a]"><Plus className="h-4 w-4" />Create Proposal</button>} /><DataTable headers={['Proposal #', 'Sent Date', 'Status', 'Amount', 'Actions']} rows={[["PROP-2026-001", 'Jul 1, 2026', <span key="status" className="rounded-full border border-[#eeb7b2] bg-blue-100 px-3 py-1 text-xs font-medium text-blue-700">Sent</span>, 'KSh 40,824.00', <button key="view" aria-label="View proposal" className="text-slate-600 hover:text-[#cc2622]"><Eye className="ml-auto h-4 w-4" /></button>]]} /></Panel><Panel><SectionHeading title="Invoices" subtitle="Invoice history for this event" action={<button className="inline-flex items-center gap-2 rounded-md bg-[#cc2622] px-4 py-2 text-sm font-semibold text-white hover:bg-[#a01f1a]"><Plus className="h-4 w-4" />Create Invoice</button>} /><EmptyBox icon={<ReceiptText className="h-9 w-9" />} message="No Invoices Created Yet" /></Panel><Panel><SectionHeading title="Payment History" subtitle="Payments received for this event" action={<OutlineButton><Banknote className="h-4 w-4" />Record Payment</OutlineButton>} /><EmptyBox icon={<Banknote className="h-9 w-9" />} message="No Payments Recorded Yet" /></Panel></div><aside className="space-y-6"><Panel><SectionHeading title="Event Totals" subtitle="Summary of all charges" /><div className="space-y-4 text-sm"><Total label="Menu Items" value="KSh 0.00" /><Total label="Item Total" value="KSh 0.00" /><div className="border-t border-[#efb6b0]" /><Total label="Service Charge (20%)" value="KSh 0.00" /><Total label="Sales Tax (5%)" value="KSh 0.00" /><div className="border-t border-blue-200 pt-4"><Total label={<span className="text-xl font-bold">Total</span>} value={<span className="text-xl font-bold">KSh 0.00</span>} /></div></div></Panel><div className="space-y-3"><OutlineButton className="w-full"><FileText className="h-4 w-4" />Create Report</OutlineButton><OutlineButton className="w-full"><ClipboardList className="h-4 w-4" />Create Proposal</OutlineButton><button className="flex w-full items-center justify-center gap-2 rounded-md bg-[#cc2622] px-4 py-3 text-sm font-semibold text-white hover:bg-[#a01f1a]"><ReceiptText className="h-4 w-4" />Create Invoice</button></div></aside></div>
}
function Metric({ label, value, emphasis = false }: { label: string; value: string; emphasis?: boolean }) { return <Panel className="p-5"><p className="text-xs font-semibold uppercase text-slate-600">{label}</p><p className={`mt-3 text-xl font-bold ${emphasis ? 'text-[#cc2622]' : ''}`}>{value}</p></Panel> }
function EmptyBox({ icon, message }: { icon: React.ReactNode; message: string }) { return <div className="flex min-h-48 flex-col items-center justify-center rounded-lg border-2 border-dashed border-[#efb6b0] text-slate-600">{icon}<p className="mt-4 text-sm font-medium">{message}</p></div> }
function Total({ label, value }: { label: React.ReactNode; value: React.ReactNode }) { return <div className="flex items-start justify-between gap-4"><span>{label}</span><span className="font-medium text-slate-900">{value}</span></div> }
